### ISSUE TITLE
Chess Team

### ISSUE THREAD

**Issue by n8hopp** [n8hopp/GameStateInClass#11]
-Game crashed when a computer was on one card and it was its turn to make a move
-Random error where I placed all my cards but didn't get the win (said I have 1 card but no cards were visible on screen)
-Crashed after human player played a draw two card and then the computer player tried to make a move
-Don't know how it happened, but the seekbar didn't change the view of the cards so it only show one card in hand when there are three
-Spamming draw button once at 11 cards game crashes. Not sure if it is the spamming of the button, having too m any cards drawn or a combination of both.

**Comment by n8hopp** [comment]
Shogi Team Comments:

- Drawing cards multiple times caused game to crash.
- Was not given opportunity to place draw 4 cards, game automatically added 4 cards (another issue applied multiple +4 in a row and eventually crashed game).

**Comment by n8hopp** [comment]
Team Quarto:
- Program crashed when computer was on its last card and was about to make their move
- Certain instances where seek bar was unable to show the user's complete array of cards (e.g., could only see 3 cards at any given moment, even if we had more than 3 cards and we modified the progress of the seek bar)
- Program possibly crashes if you have too many cards in your hand (had around 40 cards at the time of the crash)

**Comment by millerl23** [comment]
We are addressing the crashing resulting from spamming the draw and place card locations. The non-win error has been resolved with the disappearing card issue resolution, that also addresses all of the issues mentioning the seekbar. We are aware that one crash condition was occurring when re-shuffling the deck after it has been exhausted, that has been resolved. We are trying to resolve the other crashes by keeping the player from being able to touch the table view at all when not their turn. 

Will close once that last issue is resolved

**Comment by HenrySchiffUP** [comment]
The game will no longer crash and we have fixed the win condition error. The seekbar will no longer hide certain cards in your hand.
