### ISSUE TITLE
Uno Issues - Checkers Group

### ISSUE THREAD

**Issue by n8hopp** [n8hopp/GameStateInClass#12]
- Game crashes randomly in the middle of gameplay
- Textview num cards doesn't always equal actual number of cards
- Exit button doesn't work
- No restart button
- No UNO BUTTON///

**Comment by millerl23** [comment]
Again, we have been troubleshooting crashes and believe we have the issue nailed down and are working on it. It is a concurrent modification error.

Textview issue was likely the disappearing card issue which has been resolved (if hand size <= 4, re-draw player hand from 0-3 and dont allow scrolling until hand size > 4)

Exit and Restart button now work with the menu button in the top right

Uno button is being implemented as we speak, this will close once that gets finished

**Comment by millerl23** [comment]
Didn't mean to close so I reopened

**Comment by HenrySchiffUP** [comment]
After synchronizing some code and fixing a card selection bug, the game will no longer crash in the middle of gameplay.
