### ISSUE TITLE
Crazy Eights Team Issue

### ISSUE THREAD

**Issue by n8hopp** [n8hopp/GameStateInClass#13]
Bugs:
- Crashes occasionally

Friendly Suggestions:
- Reduce the lag on the scrollbar?
- Make player turn faster

**Comment by millerl23** [comment]
Made the scrollbar smoother, we decided to leave the turn as long as it is to give the user time to read the last action which is essential in understanding when a player placed a skipping card (+2, +4, skip). Have been troubleshooting a few crashes but the description here is too vague to leave this issue open for just that.
