### ISSUE TITLE
Uno Bugs

### ISSUE THREAD

**Issue by msurur** [n8hopp/GameStateInClass#6]
1. If the game starts on a wild, doesn’t let you play the cards in your hand.
2. Can’t track the discard pile.
3. Add player Id for each hand. 

-Checkers group

**Comment by millerl23** [comment]
Issue 1 will resolve once complete implementation of wild cards occurs. We are not sure that the tracking on the discard pile is necessary for a player to know. Player names on opponent hands will be good to add.

**Comment by millerl23** [comment]
Issue with the starting wild card is resolved. Player names are added. We deemed the tracking of the discard deck not necessary.
