### ISSUE TITLE
Team Quarto - Bugs

### ISSUE THREAD

**Issue by leonor24-CS** [n8hopp/GameStateInClass#7]
- a +4 in the user's hand is blue
- the dumb AI feels really hard to play against

**Comment by millerl23** [comment]
This ticket will resolve with complete implementation of wild cards. The issue is that the wild card was not reset to blue when the deck was re-shuffled.

**Comment by millerl23** [comment]
We decided a notice that the player should try to play a card is unnecessary. They should be trying to win if they WANT to play the game.
