### ISSUE TITLE
Team Shogi Comments

### ISSUE THREAD

**Issue by torresb24** [n8hopp/GameStateInClass#8]
Might want to put a cap on the cards you can draw, tested up to 36 cards but theoretically, you could pull from pile indefinitely, might want to put some sort of check that warns player that pulling from pile is not necessary

great game!

**Comment by millerl23** [comment]
We will consider this, but if a player is knowingly continually drawing from the deck then they have no desire to win and aren't really playing the game. May end up just closing this.
